# Mixup 0.2 + CW confidence weighting
active_dataset: BSD10k-v1.2
datasets:
  BSD10k-v1.2:
    metadata_csv: "./data/BSD10k-v1.2/metadata/BSD10k_metadata.csv"
    audio_emb_folder: "./data/BSD10k-v1.2/features/clap_audio_embeddings"
    text_emb_folder: "./data/BSD10k-v1.2/features/clap_text_embeddings"
    class_names: "./data/BSD10k-v1.2/metadata/BST_description.csv"
output_path: "data"
model_output_dir: "model_output_mixup02_cw"
processed_dataset_csv: "processed_dataset.csv"
class_dict_json: "class_dict.json"
top_class_dict_json: "top_class_dict.json"
top_class_subclass_dict_json: "top_class_subclass_dict.json"
emb_size_audio: 512
emb_size_text: 512
modes:
  - both
  - audio
mixup_alpha: 0.2
use_confidence_weighting: true
