# 3-Modality + BSD35k-CS extra data (CLAP audio + CLAP text + Whisper audio)
active_dataset: BSD10k-v1.2
datasets:
  BSD10k-v1.2:
    metadata_csv: "./data/BSD10k-v1.2/metadata/BSD10k_metadata.csv"
    audio_emb_folder: "./data/BSD10k-v1.2/features/clap_audio_embeddings"
    text_emb_folder: "./data/BSD10k-v1.2/features/clap_text_embeddings"
    aux_emb_folder: "./data/BSD10k-v1.2/features/whisper_audio_embeddings"
    class_names: "./data/BSD10k-v1.2/metadata/BST_description.csv"
  BSD35k-CS:
    metadata_csv: "./data/BSD35k-CS/metadata/BSD35k-CS_metadata.csv"
    audio_emb_folder: "./data/BSD35k-CS/features/clap_audio_embeddings"
    text_emb_folder: "./data/BSD35k-CS/features/clap_text_embeddings"
    aux_emb_folder: "./data/BSD35k-CS/features/whisper_audio_embeddings"
extra_datasets:
  - BSD35k-CS
output_path: "data_3mod_35k"
model_output_dir: "model_output_3mod_35k"
processed_dataset_csv: "processed_dataset.csv"
class_dict_json: "class_dict.json"
top_class_dict_json: "top_class_dict.json"
top_class_subclass_dict_json: "top_class_subclass_dict.json"
emb_size_audio: 512
emb_size_text: 512
emb_size_aux: 512
modes:
  - both
mixup_alpha: 0.2
