# BEATs + Hierarchical Loss
# Audio: BEATs (768-dim), Text: CLAP (512-dim)
# Loss: CE(child) + 0.5 * CE(parent)

# INPUT PATHS 
active_dataset: BSD10k-v1.2
datasets:
  BSD10k-v1.2:
    metadata_csv: "./data/BSD10k-v1.2/metadata/BSD10k_metadata.csv"
    audio_emb_folder: "./data/BSD10k-v1.2/features/beats_audio_embeddings"
    text_emb_folder: "./data/BSD10k-v1.2/features/clap_text_embeddings"
    class_names: "./data/BSD10k-v1.2/metadata/BST_description.csv"

  BSD35k-CS:
    metadata_csv: "./data/BSD35k-CS/metadata/BSD35k-CS_metadata.csv"
    audio_emb_folder: "./data/BSD35k-CS/features/clap_audio_embeddings"
    text_emb_folder: "./data/BSD35k-CS/features/clap_text_embeddings"
    class_names: "./data/BSD35k-CS/metadata/BST_description.csv"

# OUTPUT PATHS
output_path: "data_beats"
model_output_dir: "model_output_beats_hloss"
processed_dataset_csv: "processed_dataset.csv"
class_dict_json: "class_dict.json"
top_class_dict_json: "top_class_dict.json"
top_class_subclass_dict_json: "top_class_subclass_dict.json"

# MODEL SETTINGS
emb_size_audio: 768
emb_size_text: 512
modes:
  - both
  - audio

# HIERARCHICAL LOSS
top_class_loss_weight: 0.5
